language: java
sudo: false
install: true

jdk:
  - openjdk9

addons:
  sonarcloud:
    organization: "default"

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=com.hello2morrow:sonar-sonargraph-integration

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false